Firmware/I2C.c

For I2C reads, rearrange the printing of messages to _after_ the ACK is generated. This adds about 0.4 ms of space between the ACK of one byte and the first bit of the next. Many devices need to clock stretch between here, but can't with v3 hardware. This fixes issues with bulk reads on many I2C devices, provided they don't need to stretch the clock longer than 0.4 ms.
(to be clear, this doesn't add extra time between bytes, it removes 0.4 ms that was happening before the ACK, and moves it to after)

rearrange order of ACK in I2Cread

---

Firmware/baseIO.c
Firmware/baseIO.h
Firmware/basic.c
Firmware/jtag.c
Firmware/onboardEEPROM.c
Firmware/procMenu.c
Firmware/smps.c

There appears to be a long-standing bug that causes an endless loop when attempting the "Jump to bootloader" menu option:
http://dangerousprototypes.com/forum/viewtopic.php?f=4&t=5052&p=54931
Both onboardEEPROM.c and smps.c contain functions only called in the V4 variant and utilize resources not created for V3 (causing compilation errors).  Enclosing these functions with an ifdef (as is done with other code in Bus Pirate) allows these files to compile in V3 without needing a different project file.

bug fix for "Jump to bootloader" and use of BUSPIRATEV4 define where needed

---

Firmware/1wire.c
Firmware/I2C.c
Firmware/SPI.c
Firmware/UART.c
Firmware/baseIO.c

Resource usage compared to 65bc53297ea98fe6f36ac6a301e0d2c19d12d88f:
RAM: 11912 -> 11600 (-312)
ROM: 59224 -> 59306 (+82)

Mark constant tables as "const".

---

Firmware/procMenu.c

../procMenu.c: In function 'serviceuser':
../procMenu.c:74:14: error: 'stop' may be used uninitialized in this function
../procMenu.c:75:9: error: 'newstart' may be used uninitialized in this function
../procMenu.c:76:9: error: 'oldstart' may be used uninitialized in this function
../procMenu.c:471:23: error: 'oldDmode' may be used uninitialized in this function

Fixed 4 warnings that are treated as errors in a new compiler

---

BPv4-bootloader/firmware-v1/picusb.h
Firmware/hd44780.c

I don't know how nobody met this problem before, maybe the older MPLABs were not case sensitive regarding the header file names. After this change it compiles... My build environment: Ubuntu Linux 16.04.1 x64, MPLAB X v3.40 and MPLAB XC v1.26 compiler with PRO mode enabled (60 days free evaluation license, so that I could enable "3" level optimization for speed)

Fix ../hd44780.c:21:17: fatal error: SPI.h: No such file or directory

---

Firmware/dp_usb/cdc.c

See more information here - https://github.com/BusPirate/Bus_Pirate/issues/11

No inline for WaitOutReady() to fix "symbol .loopOut is already defined"

---

BPv4-bootloader/firmware-v1/bootloader.c

I think that this version increase is deserved because it never increased for many years (probably since BPv4 release)

increase bootloader version from 4.06 to 4.10

---

Firmware/proc_menu.c

Call the correct function to wait for Empty TX
Corrects typo of 'until'
It seems the issue was addressed in commit [597926a](https://github.com/BusPirate/Bus_Pirate/commit/597926a28f90839c6ff4a730d028955199f1fbb9)
Need to remove incorrect description

Call the correct function to wait for Empty TX

---

Bootloaders/BPv3-bootloader/firmware-v4.5/p24FJ64GA002.gld
Bootloaders/BPv3-bootloader/upgrader-v2tov4/APP 24FJ64GA002.gld
Bootloaders/BPv3-bootloader/upgrader-v4tov4/p24FJ64GA002.gld
Firmware-Alternates/Blink_MODE_LED/p24FJ64GA002.gld
Firmware-Alternates/firmware-STK500v2/p24FJ64GA002.gld
Firmware-Alternates/firmware-XSVFplayer/p24FJ64GA002.gld
Firmware/p24FJ256GB106.gld
Firmware/p24FJ64GA002.gld

XC16 1.30 and newer will produce a linker warning if CRT_STARTMODE
is not set. The script fragment is copied directly from the compiler
distribution.

Set CRT_STARTMODE in linker scripts

---

Firmware/dp_usb/cdc.c

XC16 1.31 also requires the workaround from commit 94c96d7c, so
generalize the condition.

Fix USB comms for optimized builds

---

Bootloaders/BPv4-bootloader/firmware-v1/usb_stack.h
Firmware/dp_usb/cdc.c
Firmware/dp_usb/picusb.h

The USB buffer descriptor BDSTAT field was not marked as volatile,
which turned polling functions like WaitOutReady() into infinite loops
when optimizations were enabled.
Self-test passes even when built with -O3.

Fix USB communications when optimizations are enabled

---

Firmware/busPirate.X/nbproject/configurations.xml
Firmware/messages.c
Firmware/messages.h
Firmware/messages_v3.h
Firmware/messages_v3.s
Firmware/messages_v4.h
Firmware/messages_v4.s
tools/packstrings/packstrings.py

Change string packer to place each string in a separate section.
Change message functions to take a pointer instead of an offset.
Enable linker garbage collection in project settings.
Fixes #20

Use linker garbage collection to remove unused strings

---

Firmware/messages.c
Firmware/messages.h
Firmware/messages_v3.h
Firmware/messages_v4.h
tools/packstrings/packstrings.py

On parts with more than 64KiB flash, function pointers are implemented
using 16-bit "handles". Use __builtin_tbladdress() to pass the full
address to the message printing functions.
Remove unnecessary index arithmetic from bp_message_write_buffer().
Fixes #61.

Use full addresses for printing constant messages

---

Firmware/messages.c
Firmware/messages.h
Firmware/messages_v3.h
Firmware/messages_v3.s
Firmware/messages_v4.h
Firmware/messages_v4.s
tools/packstrings/packstrings.py

Use null-terminated strings instead of passing the length as a
parameter.
This saves about 670 bytes of code space on v3, and 990 bytes on v4.

Use null-terminated strings

---

Firmware/base.c

The UART was incorrectly initialized leading to no sign of life when connecting to a BusPirate (tested on board v 3.5)

Fixed UART1 initialization

---

Firmware/base.c

Previously the printing of decimal numbers would work incorrectly, making the numbers in the menu go: 10, 20, 30 etc and display non numeric characters for numbers greater than 9.

Fixed printing of decimal numbers

---

Firmware/base.c

Not sure if this is the best way to fix it but this worked for me.
If zero is passed to the bp_write_dec_* functions to be printed then nothing will end up on screen.
This can be see if you try to run the self test and no errors are reported.
ex. "Found  errors."
A simple fix was to just check for zero and handle it explicitly.

Fix printing zero on console

---

Bootloaders/BPv4-bootloader/pirate-loader/.gitignore

This just adds a gitignore file to suppress build output in the BPv4 version of pirate-loader.

Ignore cmake output files in pirate-loader v4

---

.gitignore

This corrects a case error in the gitignore for some of the MPlab output files that wouldn't have mattered on Windows but is significant on Linux.

Correct case in gitignore for firmware

---

Firmware/openocd.c

This pull request includes the following fixes:
- wrong order (interleave) in receiving tdi_data_out and tms_data_out from openocd
- wrong byte order (MSB/LSB) in sending tdo_data_in back to openocd
- avoid sending a superfluous last tdo_data_in byte

some openocd fixes for BPv4

---

Firmware/openocd.c

This PR fixes a "GERBER" (off-by-one error) in the JTAG code in BPv4.
If an exact multiple of 8 bits was requested to be clocked out, this caused some bytes in the serial input stream (communication between openocd  and BPv4) to be lost, resulting in failure of the serial connenction.

fix off-by-one error if BPv4 JTAG code

---

Firmware/proc_menu.c

Base converter was broken during refactoring (0e01be84dc2c4e43d6330f1356deee867762e291). This PR brings it back to life.

Fix base converter

---

Firmware/spi.c

bytes_to_write was tested twice by mistake.

spi_read_write_io(): Fix buffer size test

---

Documentation/bitbang.md
Documentation/uart.md
README.md

Added an external links heading to uart doc, and provided a link, ie. asciicast demoing how to use a bus pirate to connect to a Raspberry Pi provided by the GPIO uart on a Raspberry Pi.

Add external links section to uart doc

---

Firmware/openocd.c
Firmware/proc_menu.c

Fixes #163 
I ran into the same issue compiling the firmware for the first time. These seem like pretty straightforward fixes to me, but I could be wrong. I have very little experience with the Bus Pirate, and was unable to even confirm that I'm hitting these code paths, but the firmware compiles now and I believe these are equivalent statements.
> ../openocd.c:215:7: error: implicit declaration of function 'min'
Remove calls to `min()` since I can't find it in the headers. I suspect there _is_ a `min` function we could use for readability, but I don't see it declared anywhere in XC16's `microchip/xc16/v2.00/include` directory, and there were only two instances in a single file, so this seemed okay.
> ../proc_menu.c: In function 'remove_current_character_from_command_line':
> …

Fix compile errors with XC16 v2.00
